name: Walmart Store - MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar UV
        uses: astral-sh/setup-uv@v3

      - name: Instalar dependências
        run: uv sync

      - name: Rodar testes unitários
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: uv run pytest tests/
